COPY tugrafa.swipes (card_id, datetime, poi) FROM './data/processed_dati_2014.csv' WITH HEADER=TRUE;
COPY tugrafa.swipes (card_id, datetime, poi) FROM './data/processed_dati_2015.csv' WITH HEADER=TRUE;
COPY tugrafa.swipes (card_id, datetime, poi) FROM './data/processed_dati_2016.csv' WITH HEADER=TRUE;
COPY tugrafa.swipes (card_id, datetime, poi) FROM './data/processed_dati_2017.csv' WITH HEADER=TRUE;
COPY tugrafa.swipes (card_id, datetime, poi) FROM './data/processed_dati_2018.csv' WITH HEADER=TRUE;
COPY tugrafa.swipes (card_id, datetime, poi) FROM './data/processed_dati_2019.csv' WITH HEADER=TRUE;
COPY tugrafa.swipes (card_id, datetime, poi) FROM './data/processed_dati_2020.csv' WITH HEADER=TRUE;